name: build

on: push
jobs:
  my-job:
    runs-on: self-hosted
    steps:
      - name: get arkade
        run: curl -sLS https://get.arkade.dev | sudo sh
      - name: get kind
        run: arkade get kind
      - name: get kubectl
        run: arkade get kubectl
      - name: Install Kubernetes kind
        run: |
          mkdir -p $HOME/.kube/
          $HOME/.arkade/bin/kind create cluster
      - name: Wait for nodes to be ready
        run: |
          for i in {1..10};
          do
            retVal=$(kubectl wait --for=condition=ready node --all --timeout=300s || echo -n "retry")

            if [ "$retVal" -nq "retry" ];
            then
              echo "Node ready"
              break
            fi
            sleep 2
          done
      - name: Wait until CoreDNS is ready
        run: |
          $HOME/.arkade/bin/kubectl rollout status deploy/coredns -n kube-system --timeout=300s
      - name: Explore nodes
        run: $HOME/.arkade/bin/kubectl get nodes -o wide
      - name: Explore pods
        run: $HOME/.arkade/bin/kubectl get pod -A -o wide
      - name: Show kubelet logs
        run: docker exec kind-control-plane journalctl -u kubelet

