name: build

on: push
jobs:
  my-job:
    runs-on: actuated
    steps:
      - name: get arkade
        uses: alexellis/setup-arkade@v1
      - name: get kind and kubectl
        run: |
          arkade get kind kubectl
          kubectl version
          $HOME/.arkade/bin/kubectl version
      - name: Install Kubernetes kind
        run: |
          mkdir -p $HOME/.kube/
          kind create cluster
      - name: Wait for nodes to be ready
        run: |
          for i in {1..10};
          do
            retVal=$(kubectl wait --for=condition=ready node --all --timeout=300s || echo -n "retry")

            if [ "$retVal" -nq "retry" ];
            then
              echo "Node ready"
              break
            fi
            sleep 2
          done
      - name: Wait until CoreDNS is ready
        run: |
          kubectl rollout status deploy/coredns -n kube-system --timeout=300s
      - name: Explore nodes
        run: kubectl get nodes -o wide
      - name: Explore pods
        run: kubectl get pod -A -o wide
      - name: Show kubelet logs
        run: docker exec kind-control-plane journalctl -u kubelet

